import { Button, GridBox, LineEdit, HorizontalBox, VerticalBox, ComboBox, StandardListView, StandardButton, TextEdit, ListView, CheckBox } from "std-widgets.slint";

export enum PaneId { left, right }

export struct Line {
	text: string,
	striked: bool,
}

component DiffPane inherits VerticalBox {
    in property <[Line]> lines;
    in property <[Line]> diff;
    in property <string> title;

    property <[Line]> current: diff;

    callback import();
    callback export();
    callback open();
    callback reload();

    HorizontalLayout {
        spacing: 5px;
        alignment: stretch;

        Text {
            text: title;
            horizontal-alignment: left;
            vertical-alignment: center;
            horizontal-stretch: 1;
            vertical-stretch: 1;
        }

        Button {
            text: "Reload";
            clicked => {
                reload()
            }
        }

        is-diff := CheckBox {
            text: "Diff";
            checked: true;
        }
    }

    HorizontalLayout {
        spacing: 5px;

        Button {
            text: "Open Folder";
            clicked => {
                open()
            }
        }

        Button {
            text: "Import JSON";
            clicked => {
                import()
            }
        }

        Button {
            text: "Export JSON";
            clicked => {
                export()
            }
        }
    }

    ListView {
        for line in current: Rectangle {
            width: parent.width;
            height: 24px;
            TouchArea {
                clicked => {
                    line.striked = !line.striked;
                }
            }

            text := Text {
                x: 0;
                text: line.text;
                horizontal-alignment: left;
            }

            states [
                striked when line.striked: {
                    text.color: gray;
                }
            ]
        }
    }

    states [
        all when !is-diff.checked: {
            root.current: root.lines;
        }
    ]
}

export component AppWindow inherits Dialog {
    // default-font-family: "monospace";
	default-font-size: 16px;
    title: "Dir Diff";
    icon: app-icon;

    in property <image> app-icon;

    public function set-lines(which: PaneId, lines: [Line]) {
        if which == PaneId.left {
            left.lines = lines;
        } else {
            right.lines = lines;
        }
    }

    public function set-diff(which: PaneId, lines: [Line]) {
        if which == PaneId.left {
            left.diff = lines;
        } else {
            right.diff = lines;
        }
    }

    public function set-title(which: PaneId, title: string) {
        if which == PaneId.left {
            left.title = title;
        } else {
            right.title = title;
        }
    }

    callback import(PaneId);
    callback export(PaneId);
    callback open(PaneId);
    callback reload(PaneId);

    HorizontalLayout {
        left := DiffPane {
            export => {
                root.export(PaneId.left)
            }
            import => {
                root.import(PaneId.left)
            }
            open => {
                root.open(PaneId.left)
            }
            reload => {
                root.reload(PaneId.left)
            }
        }

        right := DiffPane {
            export => {
                root.export(PaneId.right)
            }
            import => {
                root.import(PaneId.right)
            }
            open => {
                root.open(PaneId.right)
            }
            reload => {
                root.reload(PaneId.right)
            }
        }
    }
}
